server:
  port: 9020

spring:
  application:
    name: mycloud-order
  cloud:
    circuit:
      breaker:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false

  datasource:
    druid:
      max-wait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 默认开启，当前已开启
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      # 默认关闭，需手动开启，当前已开启
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      # 默认关闭，需手动开启，当前已开启
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      # 默认关闭，需手动开启，当前已关闭
      config:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      web-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      aop-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      stat-view-servlet:
        enabled: true
        login-username: admin
        reset-enable: true
        login-password: 123456

      url: jdbc:mysql://192.168.105.80:3306/messagedemo1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456

logging:
  level:
    root: INFO
  file: D:/logs/${spring.application.name}/${spring.application.name}.log

rocketmq:
  namesrv:
    addr: 192.168.105.80:9876

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9040/eureka/,http://localhost:9041/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management.security.enabled: false

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

resttemplate:
  ReadTimeout: 3000
  ConnectTimeout: 3000

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 15000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy:  THREAD #SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

