server:
  port: 9050

spring:
  application:
    name: mycloud-admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9040/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true

management.security.enabled: false